### ISSUE TITLE
Week 14 Project Feedback Feedback

### ISSUE THREAD

**Issue by emily1129** [CryptoEpsilon/SecretSheath-app#4]
1. There is no `StringSecurity` library, please implement it. 
https://github.com/CryptoEpsilon/SecretSheath-app/blob/d6edb3c15d37e751904f63b3610e4c9a5a49a95e/app/forms/auth.rb#L34-L36

**Comment by soumyaray** [comment]
Please consider adding a test that you are only accepting passwords of adequate entropy. (The password registration form object should ensure adequate entropy)

**Comment by supakarn-j** [comment]
The `StringSecurity` library is miplemented in the final commit
